=== community-ssu/gtk/gazpacho/catalogs/glade-catalog.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT glade-catalog (glade-widget-classes?, 
                         glade-widget-group*)>

<!ATTLIST glade-catalog name            CDATA #REQUIRED
                        priority        CDATA #IMPLIED
                        library         CDATA #IMPLIED
                        library-type    (c|python) #IMPLIED
                        requires        CDATA #IMPLIED>

<!ELEMENT glade-widget-classes (glade-widget-class+)>

<!ELEMENT glade-widget-class (tooltip?,
		                      packing-defaults?)>

<!ATTLIST glade-widget-class name          CDATA #REQUIRED
                             generic-name  CDATA #IMPLIED
			                 title         CDATA #IMPLIED
			                 adaptor-class CDATA #IMPLIED
                             register-type-function CDATA #IMPLIED>

<!ELEMENT glade-widget-group (glade-widget-class-ref+)>

<!ATTLIST glade-widget-group name  CDATA #REQUIRED
                             title CDATA #REQUIRED>

<!ELEMENT glade-widget-class-ref EMPTY>
<!ATTLIST glade-widget-class-ref name CDATA #REQUIRED>

<!ELEMENT packing-defaults (parent-class+)>

=== community-ssu/gtk/gazpacho-hildon/hildonwidgets.xml
<?xml version="1.0"?>
<!DOCTYPE glade-catalog SYSTEM "glade-catalog.dtd">
<glade-catalog name="hildonwidgets" library="hildon">
  <glade-widget-classes>

    <!-- Hildon Widgets -->
    <glade-widget-class name="HildonColorButton"
                        generic-name="colorbutton"
                        title="Color Button"/>

    <glade-widget-class name="HildonDateEditor"
                        generic-name="dateeditor"
			title="Date Editor"
                        adaptor-class="ContainerWithNoChildrenAdaptor"/>

    <glade-widget-class name="HildonTimeEditor"
                        generic-name="timeeditor"
			title="Time Editor"
                        adaptor-class="ContainerWithNoChildrenAdaptor"/>

    <glade-widget-class name="HildonWeekdayPicker"
                        generic-name="weekdaypicker"
                        title="Weekday Picker"
                        adaptor-class="ContainerWithNoChildrenAdaptor"/>

    <glade-widget-class name="HildonNumberEditor"
                        generic-name="numbereditor"
			title="Number Editor"
                        adaptor-class="ContainerWithNoChildrenAdaptor"/>

    <glade-widget-class name="HildonRangeEditor"
                        generic-name="rangeeditor"
			title="Range Editor"
                        adaptor-class="ContainerWithNoChildrenAdaptor"/>

    <glade-widget-class name="HildonVolumebar" 
                        adaptor-class="ContainerWithNoChildrenAdaptor"/>

    <glade-widget-class name="HildonHVolumebar" 
                        generic-name="hvolumebar"
			title="Horizontal Volumebar"/>
		
    <glade-widget-class name="HildonVVolumebar"
                        generic-name="vvolumebar"
			title="Vertical Volumebar"/>

    <glade-widget-class name="HildonControlbar"
                        generic-name="controlbar"
			title="Controlbar"/>

    <glade-widget-class name="HildonSeekbar"
                        generic-name="seekbar"
			title="Seekbar"/>

    <glade-widget-class name="HildonFindToolbar"
                        generic-name="findtoolbar"
			title="Find toolbar"
                        adaptor-class="FindToolbarAdaptor"/>

    <!-- Hildon Popups -->
    <glade-widget-class name="HildonCalendarPopup"
                        generic-name="calendarpopup"
                        title="Calendar Popup"
                        adaptor-class="ModalDialogAdaptor"/>

    <glade-widget-class name="HildonColorSelector"
                        generic-name="colorselector"
                        title="Color Selector"
                        adaptor-class="ModalDialogAdaptor"/>

    <glade-widget-class name="HildonTimePicker"
                        generic-name="timepicker"
			title="Time Picker"
                        adaptor-class="ModalDialogAdaptor"/>

    <!-- Hildon Containers -->
    <glade-widget-class name="HildonCaption"
                        generic-name="caption"
                        title="Caption"
                        adaptor-class="CaptionAdaptor"/>

<!-- The HildonGrid crashes at my environment so I have
     to disable it temporarly.
     See: https://maemo.org/bugzilla/show_bug.cgi?id=773
    <glade-widget-class name="HildonGrid"
                        generic-name="grid"
                        title="Grid"
                        adaptor-class="GridAdaptor"/>

    <glade-widget-class name="HildonGridItem"
                        generic-name="griditem"/>
-->

    <!-- Hildon Toplevels -->
    <glade-widget-class name="HildonWindow"
	    		generic-name="window"
			title="Window"
			adaptor-class="WindowAdaptor"/>

    <glade-widget-class name="HildonNote"
                        generic-name="note"
                        title="Note"
                        adaptor-class="ModalDialogAdaptor"/>

    <glade-widget-class name="HildonFileChooserDialog"
                        generic-name="filechooserdialog"
			title="File Chooser Dialog"
                        adaptor-class="FileChooserDialogAdaptor"/>

    <glade-widget-class name="HildonFontSelectionDialog"
                        generic-name="fontselectiondialog"
			title="Font Selection Dialog"
                        adaptor-class="ModalDialogAdaptor"/>

    <glade-widget-class name="HildonGetPasswordDialog"
                        generic-name="getpassworddialog"
                        title="Get Password Dialog"
			adaptor-class="ModalDialogAdaptor"/>

    <glade-widget-class name="HildonSetPasswordDialog"
                        generic-name="setpassworddialog"
                        title="SetPasswordDialog"
                        adaptor-class="ModalDialogAdaptor"/>

<!-- The HildonNamePasswordDialog has a 'name' property that conflict
     with GtkWidget's name property. The latter is a critical part
     of Gazpacho internals. So this widget is not available until that
     prop is renamed
     See: https://maemo.org/bugzilla/show_bug.cgi?id=772

    <glade-widget-class name="HildonNamePasswordDialog"
                        generic-name="namepassworddialog"
			title="Name Password Dialog"
                        adaptor-class="ModalDialogAdaptor"/>
-->

    <glade-widget-class name="HildonSortDialog"
                        generic-name="sortdialog"
                        title="Sort Dialog"
                        adaptor-class="ModalDialogAdaptor"/>

    <glade-widget-class name="HildonWizardDialog"
                        generic-name="wizarddialog"
                        title="Wizard Dialog"
                        adaptor-class="WizardDialogAdaptor"/>

  </glade-widget-classes>

  <glade-widget-group name="hildon" title="Hildon Widgets">
    	<glade-widget-class-ref name="HildonColorButton"/>
    	<glade-widget-class-ref name="HildonDateEditor"/>
    	<glade-widget-class-ref name="HildonTimeEditor"/>
    	<glade-widget-class-ref name="HildonWeekdayPicker"/>
    	<glade-widget-class-ref name="HildonNumberEditor"/>
    	<glade-widget-class-ref name="HildonRangeEditor"/>
    	<glade-widget-class-ref name="HildonHVolumebar"/>
    	<glade-widget-class-ref name="HildonVVolumebar"/>
    	<glade-widget-class-ref name="HildonControlbar"/>
    	<glade-widget-class-ref name="HildonSeekbar"/>
    	<glade-widget-class-ref name="HildonFindToolbar"/>
  </glade-widget-group>

  <glade-widget-group name="hildon-containers" title="Hildon Popups">
    	<glade-widget-class-ref name="HildonCalendarPopup"/>
    	<glade-widget-class-ref name="HildonColorSelector"/>
    	<glade-widget-class-ref name="HildonTimePicker"/>
  </glade-widget-group>
  
  <glade-widget-group name="hildon-containers" title="Hildon Containers">
    	<glade-widget-class-ref name="HildonCaption"/> 
<!--
    	<glade-widget-class-ref name="HildonGrid"/>
-->
  </glade-widget-group>

  <glade-widget-group name="hildon-toplevels" title="Hildon Toplevels">
  	<glade-widget-class-ref name="HildonWindow"/>
	<glade-widget-class-ref name="HildonNote"/>
   	<glade-widget-class-ref name="HildonFileChooserDialog"/>
   	<glade-widget-class-ref name="HildonFontSelectionDialog"/>
    	<glade-widget-class-ref name="HildonGetPasswordDialog"/>
    	<glade-widget-class-ref name="HildonSetPasswordDialog"/>

<!-- Se above for the reason this widget is disabled
    	<glade-widget-class-ref name="HildonNamePasswordDialog"/>
-->

    	<glade-widget-class-ref name="HildonSortDialog"/>
    	<glade-widget-class-ref name="HildonWizardDialog"/>
  </glade-widget-group>
</glade-catalog>
